### ISSUE TITLE
Dodge/Dash

### ISSUE THREAD

**Issue by sentient-soup** [euthyphro666/proto-ninja#10]

**Comment by swoobie** [comment]
I think this one is resolved as well

**Comment by swoobie** [comment]
What's left to do here? What's the goal of the mechanic that's missing?

**Comment by sentient-soup** [comment]
I'm not sure, I vaguely remember thinking of an aspect of it that was missing. But I don't remember and didn't write it down. So I'll close it pending me re-remembering what I thought of.
